language: python
os: linux
dist: bionic
#if: branch = master or tag IS present
python: 3.6

# important: with limited depth the tags are not cloned properly - the PBR does not work
git:
   depth: false

before_install:
  - pip install -r ./requirements-dev.txt
  - ./setup.py install

jobs:
    allow_failures:
        env:
            - CAN_FAIL=true

    include:
        - stage: Test on Python 3.6
          python: 3.6
          script: rkd :test --src-dir=src

        - stage: Test on Python 3.7
          python: 3.7
          script: rkd :test --src-dir=src

        - stage: Test on Python 3.8
          python: 3.8
          script: rkd :test --src-dir=src

        - stage: Release
          python: 3.6
          script: RKD_COMPAT_SUBPROCESS=true rkd :release
